### ISSUE TITLE
How to test it

### ISSUE THREAD

**Issue by HaiChecker** [gnosis/svalinn-kotlin#4]
How to test it, this is my error log:
Class not found: "pm.gnosis.crypto.HDNodeTest" Empty test suite.

**Comment by HaiChecker** [comment]
I know, I added the open keyword above the class

**Comment by fmrsabino** [comment]
Hi!

You can run the tests using the included Gradle Wrapper. For the `crypto` module:
```
./gradlew :crypto:testDebug
```

You can also do it in Android Studio by clicking the green arrow to the left of the test class.
![image](https://user-images.githubusercontent.com/3332770/36858310-17c1476c-1d7b-11e8-932b-dfba7f7300cf.png)

No changes to the files should be required to run the tests.

**Comment by HaiChecker** [comment]
OK, I see. Thank you.
